document:
    - cover:
        name: title_page
        template_conf: 'title_config.yaml'
        contents:
            - 'metadata.yaml'
    - page:
        name: document_information
        contents: 
            - docinfo.md
            - metadata.yaml
        template_conf: 'body_config.yaml'
    - toc:
        name: table_of_contents
        template_conf: 'toc_config.yaml'
    - page:
        name: report
        contents: 
            - 'exec.md'
            - 'intro.md'
            - 'findings/*.md'
            - 'appendix.md'
            - 'metadata.yaml'
        template_conf: 'body_config.yaml'
filename: 'pentest_report'
classification: Commercial-in-Confidence
template: 'default'
template_conf: 'document_config.yaml'

